# Generated by Django 5.2.7 on 2025-10-14 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='The name of the categoty')),
                ('description', models.TextField(blank=True, null=True, verbose_name='The description of the category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='The name of the customer')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateField(auto_now_add=True, verbose_name='The date which the order is placed')),
                ('complete', models.BooleanField(blank=True, default=False, null=True, verbose_name='Designed if the order is completed or not')),
                ('status', models.CharField(max_length=200, verbose_name='The status of the commande')),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='The ID of the transaction')),
                ('total_trans', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='The total price of the transaction')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.client', verbose_name='the customer who places the order')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='AddressChipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresse', models.CharField(max_length=100, null=True)),
                ('ville', models.CharField(max_length=100, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.commande')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='The name of the product')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='The price of the product')),
                ('digital', models.BooleanField(blank=True, null=True, verbose_name='Designed if the product is digital or not')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop', verbose_name='The image for the product presentation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='The date of the product created')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category', verbose_name='The category of the product')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='CommandeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(blank=True, null=True, verbose_name='The quantity of a article')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="The date who it's added")),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.commande', verbose_name='The order')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.produit', verbose_name='The articles')),
            ],
            options={
                'verbose_name': 'ItemOrder',
                'verbose_name_plural': 'ItemOrders',
            },
        ),
    ]
