# Generated by Django 5.2.7 on 2025-10-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['price'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='commande',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='The ID of the transaction'),
        ),
    ]
