# Generated by Django 5.2.7 on 2025-10-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(max_length=200, verbose_name='The status of the commande'),
        ),
    ]
